[package]
name = "net"
description = "Generic interfaces for Translucence web APIs."
version = "0.1.0"
authors = ["Jeb Bearer <jeb.bearer@translucence.net>"]
edition = "2018"

[dependencies]
ark-serialize = { version = "0.3.0", features = ["derive"] }
ark-std = { version = "0.3.0", default-features = false }
bincode = "1.3.3"
commit = { git = "ssh://git@github.com/SpectrumXYZ/commit.git", rev = "ce0249eb2e7cd9eb1a1df04dbe7a6f88adfc8e80" }
futures = "0.3.16"
generic-array = { version = "0.14.4", features = ["serde"] }
itertools = "0.10.1"
jf-aap = { features=["std"], git = "ssh://git@github.com/SpectrumXYZ/jellyfish-apps.git", rev = "eb8d3d3b03fec0d88327f4686e8a2787c85274d9"}
jf-utils = { features=["std"], git = "ssh://git@github.com/SpectrumXYZ/jellyfish-apps.git", rev = "eb8d3d3b03fec0d88327f4686e8a2787c85274d9"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.61"
snafu = { version = "0.6.10", features = ["backtraces"] }
surf = "2.3.1"
tagged-base64 = { git = "ssh://git@github.com/SpectrumXYZ/tagged-base64.git", branch = "main"}
tide = "0.16.0"
tracing = "0.1.26"
